version: '3.8'

services: 

  maven:
       build:
           context: ./maven
           dockerfile: dockerfile-maven
       container_name: maven_container
       volumes: 
        - ./tomcat:/home/ubuntu/homework/boxfuse/1boxfuse-sample-java-war-hello/pom.xml
         
  tomcat:
       build: 
           context: ./tomcat
           dockerfile: dockerfile-tomcat
       container_name: tomcat_container
       links: 
        - maven
       ports: 
        - 8080:8080
      
       

