FROM ubuntu:latest
RUN apt-get update
RUN apt-get install default-jdk -y 
RUN apt-get install maven -y 
WORKDIR /home/ubuntu/homework/boxfuse
RUN git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
RUN mvn package ./boxfuse-sample-java-war-hello/pom.xml